package proyecto_estructura_de_datos_sh_aq;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author santiagoh
 */

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.io.File;

public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    
    // Variables de instancia
    private Grafo grafo;
    private PanelGrafo panelGrafo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        inicializarComponentes();
    }
    
    private void inicializarComponentes() {
        grafo = new Grafo();
        panelGrafo = new PanelGrafo();
        
        // Agregar panelGrafo al panelGrafoContainer
        panelGrafoContainer.setLayout(new java.awt.BorderLayout());
        panelGrafoContainer.add(panelGrafo, java.awt.BorderLayout.CENTER);
        
        // Agregar action listeners
        CargarCSVsinapsis.addActionListener(this::CargarCSVsinapsisActionPerformed);
        CargarCSVneuro.addActionListener(this::CargarCSVneuroActionPerformed);
        Salir.addActionListener(this::SalirActionPerformed);
        btnDijkstra.addActionListener(this::btnDijkstraActionPerformed);
        btnFatiga.addActionListener(this::btnFatigaActionPerformed);
        btnAgregarNeurona.addActionListener(this::btnAgregarNeuronaActionPerformed);
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBFS = new javax.swing.JButton();
        btnDijkstra = new javax.swing.JButton();
        btnFatiga = new javax.swing.JButton();
        btnAgregarNeurona = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregarConexion = new javax.swing.JButton();
        btnEliminarNeurona = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelGrafoContainer = new javax.swing.JPanel();
        scrollResultados = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        CargarCSVsinapsis = new javax.swing.JMenuItem();
        CargarCSVneuro = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBFS.setText("Detectar Zonas Aisladas (BFS)");
        btnBFS.addActionListener(this::btnBFSActionPerformed);

        btnDijkstra.setText("Calcular Ruta Mas Rapida ");

        btnFatiga.setText("Simular Fatiga (x1.2)");

        btnAgregarNeurona.setText("Agregar Neurona ");

        btnEstadisticas.setText("Mostrar Estadistica ");

        btnGuardar.setText("Guardar Cambios ");

        btnAgregarConexion.setText("Agregar Sinapsis");
        btnAgregarConexion.addActionListener(this::btnAgregarConexionActionPerformed);

        btnEliminarNeurona.setText("Eliminar Neurona ");
        btnEliminarNeurona.addActionListener(this::btnEliminarNeuronaActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFatiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarNeurona, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarNeurona, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnSalir)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBFS)
                    .addComponent(btnAgregarNeurona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFatiga)
                    .addComponent(btnEliminarNeurona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstadisticas)
                    .addComponent(btnAgregarConexion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDijkstra)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelGrafoContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelGrafoContainer.setMinimumSize(new java.awt.Dimension(600, 400));
        panelGrafoContainer.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout panelGrafoContainerLayout = new javax.swing.GroupLayout(panelGrafoContainer);
        panelGrafoContainer.setLayout(panelGrafoContainerLayout);
        panelGrafoContainerLayout.setHorizontalGroup(
            panelGrafoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        panelGrafoContainerLayout.setVerticalGroup(
            panelGrafoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        scrollResultados.setViewportView(txtResultados);

        Archivo.setText("Archivo");

        CargarCSVsinapsis.setText("Cargar Red Neuronal");
        Archivo.add(CargarCSVsinapsis);

        CargarCSVneuro.setText("Cargar Diccionario");
        Archivo.add(CargarCSVneuro);

        Salir.setText("Salir");
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollResultados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGrafoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollResultados)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        if (grafo == null || grafo.getNumNeuronas() == 0) {
            JOptionPane.showMessageDialog(this, "Primero debe cargar una red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String input = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona origen:", "Detectar Zonas Aisladas", JOptionPane.QUESTION_MESSAGE);
        if (input == null || input.trim().isEmpty()) {
            return;
        }
        
        try {
            int idOrigen = Integer.parseInt(input.trim());
            
            if (grafo.obtenerNeurona(idOrigen) == null) {
                JOptionPane.showMessageDialog(this, "La neurona con ID " + idOrigen + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Convertir grafo al formato esperado por BFS
            TablaHash<Integer, ListaEnlazada<Integer>> grafoBFS = convertirGrafoParaBFS();
            
            // Ejecutar BFS
            ListaEnlazada<Integer> zonasAisladas = BFS.obtenerZonasAisladas(grafoBFS, idOrigen);
            
            // Resaltar zonas aisladas en el panel
            panelGrafo.resaltarZonasAisladas(zonasAisladas);
            
            // Mostrar resultados
            StringBuilder resultado = new StringBuilder();
            resultado.append("=== RESULTADOS BFS ===\n");
            resultado.append("Neurona origen: ").append(idOrigen).append("\n");
            resultado.append("Zonas aisladas detectadas: ").append(zonasAisladas.getTamaño()).append("\n");
            
            if (zonasAisladas.getTamaño() > 0) {
                resultado.append("IDs de neuronas aisladas:\n");
                for (int i = 0; i < zonasAisladas.getTamaño(); i++) {
                    resultado.append("  - ").append(zonasAisladas.obtener(i)).append("\n");
                }
            } else {
                resultado.append("No hay zonas aisladas. Todas las neuronas son alcanzables desde el origen.\n");
            }
            
            txtResultados.setText(resultado.toString());
            JOptionPane.showMessageDialog(this, resultado.toString(), "Resultado BFS", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido para el ID de la neurona.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBFSActionPerformed
    
    private void CargarCSVsinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCSVsinapsisActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo CSV de red neuronal");
        
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
            
            try {
                // Leer archivo CSV
                ListaEnlazada<String[]> datos = CargadorCSV.leerArchivo(rutaArchivo, true);
                
                if (datos.getTamaño() == 0) {
                    JOptionPane.showMessageDialog(this, "El archivo está vacío o no tiene datos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // Limpiar grafo actual
                grafo = new Grafo();
                
                // Procesar datos y crear grafo
                for (int i = 0; i < datos.getTamaño(); i++) {
                    String[] fila = datos.obtener(i);
                    
                    // Formato esperado: idOrigen, idDestino, distancia, idNeurotransmisor, coeficienteEficiencia
                    if (fila.length >= 5) {
                        int idOrigen = Integer.parseInt(fila[0]);
                        int idDestino = Integer.parseInt(fila[1]);
                        double distancia = Double.parseDouble(fila[2]);
                        String idNeuro = fila[3];
                        double coeficiente = Double.parseDouble(fila[4]);
                        
                        // Crear neuronas si no existen
                        if (grafo.obtenerNeurona(idOrigen) == null) {
                            grafo.agregarNeurona(new Neurona(idOrigen));
                        }
                        if (grafo.obtenerNeurona(idDestino) == null) {
                            grafo.agregarNeurona(new Neurona(idDestino));
                        }
                        
                        // Crear sinapsis
                        Neurona origen = grafo.obtenerNeurona(idOrigen);
                        Neurona destino = grafo.obtenerNeurona(idDestino);
                        Sinapsis sinapsis = new Sinapsis(origen, destino, distancia, idNeuro, coeficiente);
                        grafo.agregarSinapsis(sinapsis);
                    }
                }
                
                // Actualizar visualización
                panelGrafo.actualizarGrafo(grafo);
                
                JOptionPane.showMessageDialog(this, 
                    "Red neuronal cargada exitosamente.\n" +
                    "Neuronas: " + grafo.getNumNeuronas() + "\n" +
                    "Sinapsis: " + grafo.getNumSinapsis(), 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_CargarCSVsinapsisActionPerformed
    
    private void CargarCSVneuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCSVneuroActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo CSV de neurotransmisores");
        
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
            
            try {
                // Leer archivo CSV
                ListaEnlazada<String[]> datos = CargadorCSV.leerArchivo(rutaArchivo, true);
                
                if (datos.getTamaño() == 0) {
                    JOptionPane.showMessageDialog(this, "El archivo está vacío o no tiene datos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // Limpiar diccionario actual
                TablaHash<String, Neurotransmisor> diccionarioNeuro = grafo.getDiccionarioNeuro();
                
                // Procesar datos y crear neurotransmisores
                int contador = 0;
                for (int i = 0; i < datos.getTamaño(); i++) {
                    String[] fila = datos.obtener(i);
                    
                    // Formato esperado: id, nombre, efecto, velocidad, descripcion
                    if (fila.length >= 5) {
                        String id = fila[0];
                        String nombre = fila[1];
                        String efecto = fila[2];
                        double velocidad = Double.parseDouble(fila[3]);
                        String descripcion = fila[4];
                        
                        Neurotransmisor neuro = new Neurotransmisor(id, nombre, efecto, velocidad, descripcion);
                        grafo.agregarNeurotransmisor(neuro);
                        contador++;
                    }
                }
                
                JOptionPane.showMessageDialog(this, 
                    "Diccionario de neurotransmisores cargado exitosamente.\n" +
                    "Neurotransmisores: " + contador, 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_CargarCSVneuroActionPerformed
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea salir de la aplicación?", 
            "Confirmar salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
            
        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed
    
    private void btnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkstraActionPerformed
        if (grafo == null || grafo.getNumNeuronas() == 0) {
            JOptionPane.showMessageDialog(this, "Primero debe cargar una red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String inputOrigen = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona origen:", "Calcular Ruta Más Rápida", JOptionPane.QUESTION_MESSAGE);
        if (inputOrigen == null || inputOrigen.trim().isEmpty()) {
            return;
        }
        
        String inputDestino = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona destino:", "Calcular Ruta Más Rápida", JOptionPane.QUESTION_MESSAGE);
        if (inputDestino == null || inputDestino.trim().isEmpty()) {
            return;
        }
        
        try {
            int idOrigen = Integer.parseInt(inputOrigen.trim());
            int idDestino = Integer.parseInt(inputDestino.trim());
            
            if (grafo.obtenerNeurona(idOrigen) == null) {
                JOptionPane.showMessageDialog(this, "La neurona origen con ID " + idOrigen + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (grafo.obtenerNeurona(idDestino) == null) {
                JOptionPane.showMessageDialog(this, "La neurona destino con ID " + idDestino + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Ejecutar Dijkstra
            Dijkstra.ResultadoDijkstra resultado = Dijkstra.buscar(
                grafo.getAdyacencia(), 
                grafo.getDiccionarioNeuro(), 
                idOrigen
            );
            
            // Reconstruir camino
            ListaEnlazada<Integer> camino = Dijkstra.reconstruirCamino(resultado, idDestino);
            double distancia = obtenerDistancia(resultado, idDestino);
            
            // Mostrar resultados
            StringBuilder resultadoStr = new StringBuilder();
            resultadoStr.append("=== RESULTADO DIJKSTRA ===\n");
            resultadoStr.append("Origen: ").append(idOrigen).append("\n");
            resultadoStr.append("Destino: ").append(idDestino).append("\n");
            
            if (distancia == Double.MAX_VALUE || camino.getTamaño() <= 1) {
                resultadoStr.append("No existe camino entre las neuronas.\n");
            } else {
                resultadoStr.append("Distancia total: ").append(String.format("%.2f", distancia)).append("\n");
                resultadoStr.append("Camino: ");
                for (int i = 0; i < camino.getTamaño(); i++) {
                    resultadoStr.append(camino.obtener(i));
                    if (i < camino.getTamaño() - 1) {
                        resultadoStr.append(" -> ");
                    }
                }
                resultadoStr.append("\n");
            }
            
            txtResultados.setText(resultadoStr.toString());
            JOptionPane.showMessageDialog(this, resultadoStr.toString(), "Resultado Dijkstra", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar números válidos para los IDs de las neuronas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDijkstraActionPerformed
    
    private void btnFatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFatigaActionPerformed
        if (grafo == null || grafo.getNumSinapsis() == 0) {
            JOptionPane.showMessageDialog(this, "Primero debe cargar una red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea simular fatiga?\nEsto multiplicará el coeficiente de eficiencia de todas las sinapsis por 1.2.", 
            "Confirmar simulación de fatiga", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
            
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Multiplicar coeficiente de eficiencia por 1.2
            TablaHash<Integer, ListaEnlazada<Sinapsis>> adyacencia = grafo.getAdyacencia();
            Object[] claves = adyacencia.getClaves();
            
            for (Object clave : claves) {
                Integer id = (Integer) clave;
                ListaEnlazada<Sinapsis> sinapsis = adyacencia.obtener(id);
                
                if (sinapsis != null) {
                    for (int i = 0; i < sinapsis.getTamaño(); i++) {
                        Sinapsis s = sinapsis.obtener(i);
                        double nuevoCoeficiente = s.getCoeficienteEficiencia() * 1.2;
                        s.setCoeficienteEficiencia(nuevoCoeficiente);
                    }
                }
            }
            
            // Actualizar visualización
            panelGrafo.actualizarGrafo(grafo);
            
            JOptionPane.showMessageDialog(this, 
                "Simulación de fatiga completada exitosamente.\n" +
                "El coeficiente de eficiencia de todas las sinapsis ha sido multiplicado por 1.2.", 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnFatigaActionPerformed
    
    private void btnAgregarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNeuronaActionPerformed
        String input = JOptionPane.showInputDialog(this, "Ingrese el ID de la nueva neurona:", "Agregar Neurona", JOptionPane.QUESTION_MESSAGE);
        if (input == null || input.trim().isEmpty()) {
            return;
        }
        
        try {
            int id = Integer.parseInt(input.trim());
            
            if (grafo.obtenerNeurona(id) != null) {
                JOptionPane.showMessageDialog(this, "Ya existe una neurona con ID " + id + ".", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Crear y agregar neurona
            Neurona nuevaNeurona = new Neurona(id);
            grafo.agregarNeurona(nuevaNeurona);
            
            // Actualizar visualización
            panelGrafo.actualizarGrafo(grafo);
            
            JOptionPane.showMessageDialog(this, 
                "Neurona agregada exitosamente.\nID: " + id, 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido para el ID de la neurona.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarNeuronaActionPerformed
    
    private void btnAgregarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConexionActionPerformed
        if (grafo == null || grafo.getNumNeuronas() == 0) {
            JOptionPane.showMessageDialog(this, "Primero debe cargar una red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String inputOrigen = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona origen:", "Agregar Conexión", JOptionPane.QUESTION_MESSAGE);
        if (inputOrigen == null || inputOrigen.trim().isEmpty()) {
            return;
        }
        
        String inputDestino = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona destino:", "Agregar Conexión", JOptionPane.QUESTION_MESSAGE);
        if (inputDestino == null || inputDestino.trim().isEmpty()) {
            return;
        }
        
        String inputDistancia = JOptionPane.showInputDialog(this, "Ingrese la distancia:", "Agregar Conexión", JOptionPane.QUESTION_MESSAGE);
        if (inputDistancia == null || inputDistancia.trim().isEmpty()) {
            return;
        }
        
        String inputNeuro = JOptionPane.showInputDialog(this, "Ingrese el ID del neurotransmisor (ej: GLU, GABA, ACH):", "Agregar Conexión", JOptionPane.QUESTION_MESSAGE);
        if (inputNeuro == null || inputNeuro.trim().isEmpty()) {
            return;
        }
        
        try {
            int idOrigen = Integer.parseInt(inputOrigen.trim());
            int idDestino = Integer.parseInt(inputDestino.trim());
            double distancia = Double.parseDouble(inputDistancia.trim());
            String idNeuro = inputNeuro.trim();
            
            // Validar que ambas neuronas existan
            if (grafo.obtenerNeurona(idOrigen) == null) {
                JOptionPane.showMessageDialog(this, "La neurona origen con ID " + idOrigen + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (grafo.obtenerNeurona(idDestino) == null) {
                JOptionPane.showMessageDialog(this, "La neurona destino con ID " + idDestino + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar que el neurotransmisor exista en el diccionario
            if (grafo.getDiccionarioNeuro().obtener(idNeuro) == null) {
                JOptionPane.showMessageDialog(this, "El neurotransmisor con ID " + idNeuro + " no existe en el diccionario.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar que la conexión no exista ya
            ListaEnlazada<Sinapsis> vecinos = grafo.obtenerVecinos(idOrigen);
            if (vecinos != null) {
                for (int i = 0; i < vecinos.getTamaño(); i++) {
                    Sinapsis s = vecinos.obtener(i);
                    if (s.getDestino().getId() == idDestino) {
                        JOptionPane.showMessageDialog(this, "Ya existe una conexión de " + idOrigen + " a " + idDestino + ".", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }
            
            // Crear la sinapsis con coeficiente = 1.0
            Neurona origen = grafo.obtenerNeurona(idOrigen);
            Neurona destino = grafo.obtenerNeurona(idDestino);
            Sinapsis sinapsis = new Sinapsis(origen, destino, distancia, idNeuro, 1.0);
            
            // Agregar la sinapsis al grafo
            grafo.agregarSinapsis(sinapsis);
            
            // Actualizar la visualización del grafo
            panelGrafo.actualizarGrafo(grafo);
            
            JOptionPane.showMessageDialog(this, 
                "Conexión agregada exitosamente.\n" +
                "Origen: " + idOrigen + "\n" +
                "Destino: " + idDestino + "\n" +
                "Distancia: " + distancia + "\n" +
                "Neurotransmisor: " + idNeuro + "\n" +
                "Coeficiente de eficiencia: 1.0", 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar números válidos para los IDs y la distancia.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarConexionActionPerformed
    
    private void btnEliminarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNeuronaActionPerformed
        if (grafo == null || grafo.getNumNeuronas() == 0) {
            JOptionPane.showMessageDialog(this, "Primero debe cargar una red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String input = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona a eliminar:", "Eliminar Neurona", JOptionPane.QUESTION_MESSAGE);
        if (input == null || input.trim().isEmpty()) {
            return;
        }
        
        try {
            int id = Integer.parseInt(input.trim());
            
            if (grafo.obtenerNeurona(id) == null) {
                JOptionPane.showMessageDialog(this, "La neurona con ID " + id + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea eliminar la neurona " + id + "?\n" +
                "Esto también eliminará todas las sinapsis asociadas.", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
                
            if (confirmacion == JOptionPane.YES_OPTION) {
                grafo.eliminarNeurona(id);
                
                // Actualizar visualización
                panelGrafo.actualizarGrafo(grafo);
                
                JOptionPane.showMessageDialog(this, 
                    "Neurona eliminada exitosamente.\nID: " + id, 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
                
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido para el ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarNeuronaActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea salir del programa?", 
            "Confirmar salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
            
        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        if (grafo == null) {
            JOptionPane.showMessageDialog(this, "No hay datos cargados.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        StringBuilder estadisticas = new StringBuilder();
        estadisticas.append("=== ESTADÍSTICAS DE LA RED ===\n");
        estadisticas.append("Número de neuronas: ").append(grafo.getNumNeuronas()).append("\n");
        estadisticas.append("Número de sinapsis: ").append(grafo.getNumSinapsis()).append("\n");
        estadisticas.append("Número de neurotransmisores: ").append(grafo.getDiccionarioNeuro().getTamaño()).append("\n");
        
        txtResultados.setText(estadisticas.toString());
        JOptionPane.showMessageDialog(this, estadisticas.toString(), "Estadísticas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEstadisticasActionPerformed
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (grafo == null || grafo.getNumNeuronas() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos para guardar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, 
            "Función de guardar no implementada aún.\n" +
            "La red tiene " + grafo.getNumNeuronas() + " neuronas y " + grafo.getNumSinapsis() + " sinapsis.", 
            "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    // Métodos auxiliares
    
    /**
     * Convierte el grafo del proyecto al formato esperado por BFS.
     * @return TablaHash con IDs de neuronas y listas de IDs de vecinos
     */
    private TablaHash<Integer, ListaEnlazada<Integer>> convertirGrafoParaBFS() {
        TablaHash<Integer, ListaEnlazada<Integer>> grafoBFS = new TablaHash<>();
        TablaHash<Integer, ListaEnlazada<Sinapsis>> adyacencia = grafo.getAdyacencia();
        Object[] claves = adyacencia.getClaves();
        
        for (Object clave : claves) {
            Integer id = (Integer) clave;
            ListaEnlazada<Sinapsis> sinapsis = adyacencia.obtener(id);
            ListaEnlazada<Integer> vecinos = new ListaEnlazada<>();
            
            if (sinapsis != null) {
                for (int i = 0; i < sinapsis.getTamaño(); i++) {
                    Sinapsis s = sinapsis.obtener(i);
                    if (s != null && s.getDestino() != null) {
                        vecinos.agregar(s.getDestino().getId());
                    }
                }
            }
            grafoBFS.insertar(id, vecinos);
        }
        
        return grafoBFS;
    }
    
    /**
     * Obtiene la distancia desde el origen hasta un destino específico.
     * @param resultado Resultado de Dijkstra
     * @param idDestino ID de la neurona destino
     * @return Distancia calculada o Double.MAX_VALUE si no existe camino
     */
    private double obtenerDistancia(Dijkstra.ResultadoDijkstra resultado, int idDestino) {
        Double distancia = resultado.distancias.obtener(idDestino);
        return distancia != null ? distancia : Double.MAX_VALUE;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem CargarCSVneuro;
    private javax.swing.JMenuItem CargarCSVsinapsis;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton btnAgregarConexion;
    private javax.swing.JButton btnAgregarNeurona;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnDijkstra;
    private javax.swing.JButton btnEliminarNeurona;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnFatiga;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelGrafoContainer;
    private javax.swing.JScrollPane scrollResultados;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
